### ISSUE TITLE
Fill out Thermodynamics section

### ISSUE THREAD

**Issue by JIMonroe** [MobleyLab/basic_simulation_training#35]
Just needs to be done.  Any takers?  If I don't hear anything by Friday afternoon, I'll work on this while traveling.

**Comment by avisekdas** [comment]
Dear All,

Due to unforeseen administrative responsibilities and grant writing I could
not contribute to the paper. Please remove my name from the author list, if
you have not already done so.

Thank you for taking this forward and sorry for the inconveniences caused
by mine irregular response.

Thanks,
Avisek

**Comment by davidlmobley** [comment]
@JIMonroe got a draft of this in already.
